---
services:
  cache:
    image: redis:7-alpine
    volumes:
      - redis_data:/data

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      REDIS_HOST: cache
      REDIS_PORT: 6379
    restart: on-failure
    depends_on:
      - cache

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  redis_data:
